### ISSUE TITLE
Support empty password in UTA_DB_URL

### ISSUE THREAD

**Issue by richardhj** [cancervariants/variation-normalization#141]
When you set UTA_DB_URL to an URL without a password (without a colon `:`, e.g., `UTA_DB_URL=postgresql://uta_admin@localhost:5432/uta/uta_20210129`), you encounter an error.

This is because `url.password` is None: 
https://github.com/cancervariants/variation-normalization/blob/d41e9ee786b14f47d17ea8e458eed08ec00ba339/variation/data_sources/uta.py#L77

stack trace:
```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/richard/Downloads/metakb/metakb/cli.py", line 267, in <module>
    CLI().update_metakb_db()
  File "/Users/richard/.local/share/virtualenvs/metakb-uokQQFuH/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/richard/.local/share/virtualenvs/metakb-uokQQFuH/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/richard/.local/share/virtualenvs/metakb-uokQQFuH/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/richard/.local/share/virtualenvs/metakb-uokQQFuH/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/richard/Downloads/metakb/metakb/cli.py", line 99, in update_metakb_db
    CLI()._transform_sources()
  File "/Users/richard/Downloads/metakb/metakb/cli.py", line 158, in _transform_sources
    source = class_name()
  File "/Users/richard/Downloads/metakb/metakb/transform/civic.py", line 24, in __init__
    super().__init__(file_path)
  File "/Users/richard/Downloads/metakb/metakb/transform/base.py", line 20, in __init__
    self.vicc_normalizers = VICCNormalizers()
  File "/Users/richard/Downloads/metakb/metakb/normalizers.py", line 19, in __init__
    self.variation_normalizer = VariationQueryHandler()
  File "/Users/richard/.local/share/virtualenvs/metakb-uokQQFuH/lib/python3.9/site-packages/variation/query.py", line 44, in __init__
    self.uta = UTA(db_url=uta_db_url, db_pwd=uta_db_pwd)
  File "/Users/richard/.local/share/virtualenvs/metakb-uokQQFuH/lib/python3.9/site-packages/variation/data_sources/uta.py", line 31, in __init__
    self.args = self._get_conn_args(('VARIATION_NORM_EB_PROD' in environ),
  File "/Users/richard/.local/share/virtualenvs/metakb-uokQQFuH/lib/python3.9/site-packages/variation/data_sources/uta.py", line 78, in _get_conn_args
    url.username, unquote(url.password))
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/parse.py", line 656, in unquote
    if '%' not in string:
TypeError: argument of type 'NoneType' is not iterable
```

Cheers ✌️

**Comment by korikuzma** [comment]
Closing since UTA Tools handles this.
