### ISSUE TITLE
Error thrown on asymmetric single number/range intervals

### ISSUE THREAD

**Issue by theferrit32** [cancervariants/variation-normalization#417]
If one bound is a range and one is not, a runtime exception is thrown in `hgvs_to_copy_number_change` and the server responds with status `500`.

Example input: 
`NC_000018.9:g.(48556994_48573289)_48573471dup`
(https://www.ncbi.nlm.nih.gov/clinvar/variation/1878325/)

```
curl -v 'http://localhost:8002/variation/hgvs_to_copy_number_change?hgvs_expr=NC_000018.9%3Ag.%2848556994_48573289%29_48573471dup&copy_change=efo%3A0030070&do_liftover=false&untranslatable_returns_text=false'
*   Trying 127.0.0.1:8002...
* Connected to localhost (127.0.0.1) port 8002 (#0)
> GET /variation/hgvs_to_copy_number_change?hgvs_expr=NC_000018.9%3Ag.%2848556994_48573289%29_48573471dup&copy_change=efo%3A0030070&do_liftover=false&untranslatable_returns_text=false HTTP/1.1
> Host: localhost:8002
> User-Agent: curl/7.87.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< date: Mon, 08 May 2023 01:35:57 GMT
< server: uvicorn
< content-length: 21
< content-type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
Internal Server Error
```

Server stacktrace:
```
INFO:     127.0.0.1:55909 - "GET /variation/hgvs_to_copy_number_change?hgvs_expr=NC_000018.9%3Ag.%2848556994_48573289%29_48573471dup&copy_change=efo%3A0030070&do_liftover=false&untranslatable_returns_text=false HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/kferrite/dev/variation-normalization/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/kferrite/dev/variation-normalization/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/kferrite/dev/variation-normalization/venv/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/kferrite/dev/variation-normalization/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/kferrite/dev/variation-normalization/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/kferrite/dev/variation-normalization/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/kferrite/dev/variation-normalization/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/kferrite/dev/variation-normalization/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/kferrite/dev/variation-normalization/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/kferrite/dev/variation-normalization/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/kferrite/dev/variation-normalization/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/kferrite/dev/variation-normalization/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/kferrite/dev/variation-normalization/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/kferrite/dev/variation-normalization/venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/Users/kferrite/dev/variation-normalization/venv/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/kferrite/dev/variation-normalization/variation/main.py", line 566, in hgvs_to_copy_number_change
    resp = await query_handler.to_copy_number_handler.hgvs_to_copy_number_change(
  File "/Users/kferrite/dev/variation-normalization/variation/to_copy_number_variation.py", line 159, in hgvs_to_copy_number_change
    validations, warnings = await self.get_validations(
  File "/Users/kferrite/dev/variation-normalization/variation/to_vrs.py", line 133, in get_validations
    validations = await self.validator.perform(
  File "/Users/kferrite/dev/variation-normalization/variation/validators/validate.py", line 121, in perform
    results = await validator.validate(
  File "/Users/kferrite/dev/variation-normalization/variation/validators/validator.py", line 210, in validate
    await self.get_valid_invalid_results(
  File "/Users/kferrite/dev/variation-normalization/variation/validators/genomic_duplication.py", line 75, in get_valid_invalid_results
    result = await self._get_variation(
  File "/Users/kferrite/dev/variation-normalization/variation/validators/genomic_duplication.py", line 150, in _get_variation
    t, s.coordinate_type, s.alt_type, errors, ival[0], ival[1])
TypeError: 'NoneType' object is not subscriptable
```

If I change the input to `NC_000018.9:g.(48556994_48573289)_(48573471_48573471)dup` it works.

**Comment by korikuzma** [comment]
@theferrit32 We only focused on the following:
- `#dup`
- `#_#dup`
- `(?_#)_(#_?)dup`
- `(?_#)_#dup`
- `#_(#_?)dup`
- `(#_#)_(#_#)dup`
I will need to add tests for the following:
- `(#_#)_#dup`
- `#_(#_#)dup`

probably should do this for deletions too. Are there any other formats that I'm missing? We have `(#_?)_(?_#)` in #342

**Comment by korikuzma** [comment]
Okay, I made [this](https://github.com/cancervariants/variation-normalization/issues/420) issue to add support for above.
